### ISSUE TITLE
How to build skulpt-pedal.js skulpt-curriculum-ctvt.js and skulpt-curriculum-sneks.js?

### ISSUE THREAD

**Issue by alexwenbj** [blockpy-edu/blockpy#106]
How to build skulpt-pedal.js/skulpt-curriculum-ctvt.js/skulpt-curriculum-sneks.js?I ran the npm run dev in blockpy folder,but can not get these 3 files.
Thank you.

**Comment by lukesg08** [comment]
So you should actually run npm run devbuild in the skulpt directory, not the blockpy directory. And you need to specify the path to your directories pedal, curriculum-ctvt, and curriculum-sneks. You'll need to download the directories for those repos separately as well. Curriculum-ctvt is at https://github.com/pedal-edu/curriculum-ctvt, curriculum-sneks is at https://github.com/pedal-edu/curriculum-sneks, and pedal is at https://github.com/pedal-edu/pedal.

**Comment by acbart** [comment]
For convenience, the latest compiled version of the extra files you need are here:
[dependencies.zip](https://github.com/blockpy-edu/blockpy/files/5526257/dependencies.zip)

**Comment by acbart** [comment]
Long term, we need a more trivial way to get the latest version of those files; I manually composed that zip file, which is a little silly.

**Comment by acbart** [comment]
Oh and just to clarify something confusing:

You need to run `npm run devbuild` in the Skulpt directory to build the skulpt files. If you are making modifications to the BlockPy client, you also run `npm run dev` in the Blockpy directory to have it rebuild itself.

**Comment by alexwenbj** [comment]
Thank you. @acbart @lukesg08

**Comment by yaohuarun** [comment]
> pedal

how to specify the path to the directories pedal, curriculum-ctvt, and curriculum-sneks?

**Comment by Utilitycoder** [comment]
I can't seem to get blockpy to run locally. I have tried all the methods suggested here but none is working yet. How do I specify path to pedal, curriculum-ctvt, and curriculum-sneks?

**Comment by lukesg08** [comment]
Have you followed the instructions here: https://github.com/blockpy-edu/blockpy?
While earlier in this thread I said that you need to specify the file path, it's more of you need to make sure your directory structure ends up like in the installation instructions.

**Comment by Utilitycoder** [comment]
Yes I did. What I understand from the installation instructions is that blockpy-edu and pedal-edu should be subdirectories in a directory. I have done that and ran skulpt in the blockpy-edu directory. 

Here's what I got after following the instruction:

[Output after running skulpt and blockpy](https://drive.google.com/file/d/1h5Izges2iNGCCCvSIhUyAoxeb0ltZAG1/view?usp=sharing)
