### ISSUE TITLE
Similar project - Droplet

### ISSUE THREAD

**Issue by dz0** [blockpy-edu/blockpy#21]
There is a tool, called Droplet (https://github.com/droplet-editor/droplet), which is used by http://pencilcode.net and https://code.org/educate/applab
It implements issue request for JS and CofeeScript, and possibly Py(https://github.com/droplet-editor/droplet/blob/master/src/languages/python.coffee) .

Explanation, how it works http://ideas.pencilcode.net/home/htmlcss/droplet-paper.pdf

Seems a more lightweight approach than blockly...

**Comment by acbart** [comment]
Follow-up discussion at: https://groups.google.com/d/msg/blockpy/P0Ar2zPrWAg/yX7yFrAUAwAJ

**Comment by acbart** [comment]
Our new BlockMirror component (https://github.com/blockpy-edu/BlockMirror) puts us firmly in the Blockly camp. I don't know what happened to Droplet, but it doesn't seem like it's been pushed further ahead.
