### ISSUE TITLE
Reserved words get renamed to a "blockly unique name"

### ISSUE THREAD

**Issue by carlosperate** [blockpy-edu/blockpy#23]
Using any reserve words (like xrange, format, etc) in the text mode and converting it to Blockly works, but when generating the code again it sees the reserved word and renames it to a safe value (so xrange2, format2, etc).

**Comment by acbart** [comment]
Definitely a big bug - the underlying cause is a lack of py2block bindings for those relevant blocks. At some point, I need to sit down and generate those bindings. Thanks for the issue!

**Comment by acbart** [comment]
Fixed thanks to BlockMirror: https://github.com/blockpy-edu/BlockMirror/
