### ISSUE TITLE
No output handle in a block calling a function

### ISSUE THREAD

**Issue by suiato** [blockpy-edu/blockpy#27]
When I define a function in Functions with a return block and call it, the calling block has no output handle. How can I print the returned value?
(I use a cloned version running on a PC.)

**Comment by suiato** [comment]
Sorry, I was too fast to post. I found the output handle when I tried with a slight correction.

**Comment by suiato** [comment]
I closed the issue because I found the call block has an output handle when I edit the python code. But, it's still a problem that the call block doesn't have an output handle without editing the python code.

An example I ran was:
def test(x):
    return round(x)
print(test(1.5))

**Comment by acbart** [comment]
You're right, this needs to happen dynamically. It should be possible to determine, statically, if a function has a return block nested inside - and if so, then it should have a left output.

**Comment by acbart** [comment]
Static analysis is hard. Instead, BlockMirror just allows you to right click and switch between statement and expression modes for a Call block. https://github.com/blockpy-edu/BlockMirror/
