### ISSUE TITLE
Block side not always updating code

### ISSUE THREAD

**Issue by lukesg08** [blockpy-edu/blockpy#72]
When renaming variables, the code doesn't update unless you go into the text side
![CodeUpdateBug](https://user-images.githubusercontent.com/7116944/66053757-e2d6cf00-e500-11e9-95d8-eb0ab32a32d0.png)

**Comment by GuLoveShh** [comment]
hello,i‘d like to ask you a question, After my project is installed according to README, it prompts such a problem. What should I do? Uncaught TypeError: Goog. isString is not a function

**Comment by acbart** [comment]
Hello, please raise a separate Issue, do not simply post in the first issue you find.

**Comment by acbart** [comment]
This was a fix for BlockMirror, we just had to track variable renames.
